philblog/blueprints/admin.py
from flask import Blueprint, render_template, request, flash, current_app, url_for, send_from_directory, redirect, abort
from philblog.models import Article, Category
from philblog.forms import EditorForm, LoginForm
from philblog.extentions import db
import os
from datetime import datetime
from philblog.util import render_upload_file
from flask_ckeditor import upload_success, upload_fail
from flask_login import login_required

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/post/manage', methods=['GET', 'POST'])
@login_required
def post_manage():
    articles = db.session.query(Article.title, Article.id).all()
    return render_template('admin/managepost.html', articles=articles)


# todo : category should be the mutiple-checkbox..

@admin_bp.route('/post/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def post_edit(id):
    form = EditorForm()
    article = db.session.query(Article).filter(Article.id == id).first()
    if article:
        form.title.data, form.body.data = article.title, article.content
        category_old_list = article.categorys
        if request.method == 'POST':
            if form.submit.data and form.validate_on_submit():
                show_window_file = request.files.get('show_window')
                if show_window_file:
                    show_window_path = render_upload_file(show_window_file.filename, 'show_window')
                    print(show_window_path)
                    show_window_file.save(show_window_path)
                title = request.form.get('title')
                category_id = request.form.get('category')
                body = request.form.get('body')
                category = db.session.query(Category).filter(Category.id == category_id).first()
                for category_old in category_old_list:
                    article.categorys.remove(category_old)
                article.title = title
                article.content = body
                article.categorys.append(category)
                article.showwindow = show_window_file.filename
                db.session.commit()
                flash('modify the article sucessfully %s' % article.title, 'success')
                return redirect(url_for('admin.post_manage'))
            if form.discard.data:
                return redirect(url_for('admin.post_manage'))
    else:
        flash('No such article', 'error')
        abort(404)
    return render_template('admin/editpost.html', form=form)


@admin_bp.route('/post/<int:id>/drop', methods=['POST'])
@login_required
def post_drop(id):
    try:
        article = db.session.query(Article).filter(Article.id == id).first()
        db.session.delete(article)
        db.session.commit()
        flash('drop the article %s successfully !' % article.title, 'success')
    except Exception as e:
        flash('drop the article %s with error %s ' % (article.title, e), 'success')
    return redirect(url_for('admin.post_manage'))


# todo : save file logic should change to another way , flash category mapping with message color, eg.. error->red,info-->grey
@admin_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def post_new():
    form = EditorForm()
    if request.method == 'POST':
        if form.discard.data:
            title = request.form.get('title')
            message = 'drop the draft {}!'.format(title)
            flash(message, 'success')
            return redirect(url_for('admin.post_manage'))
        if form.submit.data and form.validate_on_submit():
            show_window_file = request.files.get('show_window')
            if show_window_file:
                show_window_path = render_upload_file(show_window_file.filename, 'show_window')
                print(show_window_path)
                show_window_file.save(show_window_path)
            title = request.form.get('title')
            category_id = request.form.get('category')
            body = request.form.get('body')
            category = db.session.query(Category).filter(Category.id == category_id).first()
            new_article = Article(title=title, content=body, createdate=datetime.now(),
                                  showwindow=show_window_file.filename)
            new_article.categorys.append(category)
            db.session.add(new_article)
            db.session.commit()
            flash('The article {} has successfully submitted!'.format(title), 'success')
            return redirect(url_for('admin.post_manage'))
        print(form.errors)
    return render_template('admin/newpost.html', form=form)


@admin_bp.route('/upload/', methods=['GET', 'POST'])
@login_required
def upload():
    f = request.files.get('upload')
    path = os.path.join(current_app.root_path, 'upload', f.filename)
    f.save(path)
    url = url_for('admin.getimage', filename=f.filename)
    return upload_success(url, f.filename)


@admin_bp.route('/getimage/<path:filename>', methods=['GET'])
def getimage(filename):
    return send_from_directory(os.path.join(current_app.root_path, 'upload'), filename)

philblog/blueprints/auth.py
from flask import Blueprint,request,render_template,abort,redirect,flash,url_for
from philblog.forms import LoginForm
from philblog.extentions import db,login_manager
from philblog.models import User
from flask_login import login_user,logout_user,login_required


auth_bp = Blueprint('auth',__name__)


@login_manager.user_loader
def load_user(user_id):
    if not user_id:
        return None
    else:
        curr_user = db.session.query(User).filter(User.id == int(user_id)).first()
    return curr_user


@auth_bp.route('/login',methods = ['POST','GET'])
def login():
    form = LoginForm()
    if request.method == 'POST':
        if form.login.data:
            try:
                username = request.form.get('username')
                password = request.form.get('password')
                user = db.session.query(User).filter(User.username==username,User.password==password).first()
                if user:
                    login_user(user)
                    flash('Login Successfully !','success')
                    return redirect(url_for('blog.index'))
                else:
                    flash('Login Failed! Please check the user name and password!','error')
                    return redirect(url_for('auth.login'))
            except Exception as e :
                abort(500)
    return render_template('auth/login.html',form = form)


@auth_bp.route('/logout',methods = ['GET'])
@login_required
def logout():
    logout_user()
    flash("logout!",'success')
    return redirect(url_for('blog.index'))

philblog/blueprints/blog.py
from flask import Flask, render_template, redirect, Blueprint, url_for, request, current_app, send_from_directory,flash
from philblog.extentions import db
import os
from philblog.models import Article, Category
from sqlalchemy import distinct, func

blog_dp = Blueprint('blog', __name__)


@blog_dp.route('/', defaults={'page': 1}, methods=['GET'])
@blog_dp.route('/index', defaults={'page': 1}, methods=['GET'])
@blog_dp.route('/page/<int:page>', methods=['GET'])
def index(page):
    # page = request.args.get('page',1,type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    pagination = Article.query.order_by(Article.createdate.desc()).paginate(page, per_page=per_page)
    articles = pagination.items
    # articles = Article.query.order_by(Article.createdate.desc()).limit(10).all()
    return render_template('index.html', articles=articles, pagination=pagination)


@blog_dp.route('/tag', methods=['GET'])
def tag():
    # TODO : add word cloud in here...
    categorys = Category.query.all()
    return render_template('tag.html', categorys=categorys)


@blog_dp.route('/about', methods=['GET'])
def about():
    return render_template('about.html')


@blog_dp.route('/tagged/<int:category_id>', methods=['GET'])
def tagged(category_id):
    articles = Article.query.join(Article.categorys).filter(Category.id.in_([category_id])).all()
    category = db.session.query(Category).filter(Category.id == category_id).first()
    return render_template('tagged.html', articles=articles, category=category)


@blog_dp.route('/archive', methods=['GET'])
def archive():
    createdates = db.session.query(distinct(func.date_format(Article.createdate, '%Y-%m-%d'))).order_by(
        func.date_format(Article.createdate, '%Y-%m-%d').desc())
    articles = db.session.query(Article.title, func.date_format(Article.createdate, '%Y-%m-%d'), Article.id).all()
    return render_template('archive.html', createdates=createdates, articles=articles)


@blog_dp.route('/blog/<int:post_id>', methods=['GET'])
def blog(post_id):
    id = post_id
    post = Article.query.get_or_404(id)
    return render_template('blog.html', post=post)

philblog/blueprints/search.py
from flask import Blueprint, request, abort, render_template,redirect,url_for
from philblog.models import Article

search_dp = Blueprint('search', __name__)


#todo: we should use get or post ?? should use get i think , but the get would have the json body???
#should use get method.. get usually not have the body , would put it on parameters
@search_dp.route('/_search', methods=['GET'])
def search():
    try:
        request_body = request.args
        results, number = Article.search(request_body['search'], 1, 5)
        return {"number": number, "results": [{"title": item.title, "content": item.content} for item in results]}
    except KeyError or TypeError:
        abort(400, "the request content is not correct")


@search_dp.route('/search', methods=['GET','POST'])
def search_form():
    return render_template('search.html')

philblog/templates/about.html
{% extends 'base.html' %}
{% block title %}Phillll{%endblock title%}
{% block content%}


<div class="container justify-content-center py-5">
    <div class="row">
        <div class="col-8 offset-md-2">
            <h6>Phil Gao</h6>
            <p> 毕业于重庆邮电大学，非科班出身。
                目前主要从事于微软相关的数据工程工作，包括 MSBI,PowerBI,Azure,致力于向Big Data, Machine Leaning 方向发展。<br>
                此博客是由Flask构建而成。<br>
                主要记录探讨自己工作学习中遇到的技术问题，以及自己的日常生活。
            </p>
            <p>联系我:
            <ul>
                <li><a href="https://github.com/PhilGao">Github</a></li>
                <li><a href="https://music.163.com/user/home?id=20153848">NeteaseMusic</a></li>
                <li><a href="https://space.bilibili.com/264800504">Bilibili</a></li>

            </ul>


            </p>
        </div>
    </div>
</div>


{%endblock%}

philblog/templates/archive.html
{% extends 'base.html' %}
{% block title %}Phillll{%endblock title%}
{% block content%}
<div class="container justify-content-center  py-5">

    <div class="row">
        <div class="col-8 offset-md-2">
            <section>
                {% for createdate in createdates%}
                <h5>{{createdate[0]}}</h5>
                {%for article in articles %}
                {%if article[1] == createdate[0]%}
                <p>
                    <a href="{{url_for('blog.blog',post_id = article.id)}}" class="text-dark text-capitalize">{{article.title}}</a>

                </p>
                {%endif%}
                {%endfor%}
                {%endfor%}
            </section>
        </div>
    </div>
</div>
{%endblock%}

philblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% from 'macros.html' import static_file %}
<head>
    {% block head %}
    <meta charset="UTF-8">
    {%block scripts%}
    {{static_file('js','js/jquery-3.4.0.min.js')}}
    {{static_file('js','js/popper.min.js')}}
    {{static_file('js','js/bootstrap.min.js')}}
    {{static_file('js','ckeditor/ckeditor.js')}}
    {%endblock scripts%}
    {%block styles%}
    {{static_file('css','css/bootstrap.min.css')}}
    {{static_file('css','css/catchpity.css')}}
    {%endblock styles%}
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>{% block title %}Phillll{%endblock title%}</title>
    {% endblock head%}
</head>
<body>
{% block nav%}
<nav class="navbar navbar-light bg-light py-4">
    <div class="container justify-content-sm-around">
        <a class="navbar-brand" href="{{url_for('blog.index')}}">
            <img src="{{url_for('static',filename='favicon.svg')}}" width="30" height="30"
                 class="d-inline-block align-top" alt="">
            Phillll
        </a>
        <div class="navbar-expand-lg">
            <ul class="navbar-nav">
                <li class="nav-item active mr-2 ">
                    <a class="nav-link" href="{{url_for('blog.index')}}">
                        <small>Home</small>
                    </a>
                </li>
                <li class="nav-item active mr-2">
                    <a class="nav-link" href="{{url_for('blog.tag')}}">
                        <small>Tag</small>
                    </a>
                </li>
                <li class="nav-item active mr-2">
                    <a class="nav-link" href="{{url_for('blog.archive')}}">
                        <small>Archive</small>
                    </a>
                </li>
                <li class="nav-item active mr-2">
                    <a class="nav-link" href="{{url_for('blog.about')}}">
                        <small>About</small>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="justify-content-center small">
        {% if current_user.is_authenticated %}
        <div class="dropdown">
            <button class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Welcome! | {{current_user.username}}
            </button>
            <div class="dropdown-menu dropdown-menu-sm-right">
                <a class="dropdown-item small"  href="{{url_for('admin.post_new')}}">new post</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item small" href="{{url_for('admin.post_manage')}}">Manage Posts</a>
                 <div class="dropdown-divider"></div>
                <a class="dropdown-item small" href="{{url_for('auth.logout')}}">Logout</a>
            </div>
        </div>
        {% else %}
        <span class="glyphicon glyphicon-user"></span>
        <a href="{{url_for('auth.login')}} " class="text-dark text-capitalize">Sign In</a>
        {% endif %}
    </div>
</nav>
{% endblock nav%}
{% block message%}
{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
{% for category,message in messages %}
    {% if category == 'success' %}
        <div class="alert alert-success text-center" role="alert">{{ message }}</div>
    {%elif category == 'error' %}
        <div class="alert alert-danger text-center" role="alert">{{ message }}</div>
    {% endif %}

{% endfor %}
{% endif %}
{% endwith %}
{% endblock message %}


{% block content%}
{% endblock content%}

{% block pager %}
{% endblock pager %}

{% block footer %}
<footer class="text-center">
    <small> &copy; 2019
        <a href="http://flask.pocoo.org/" title="Powered By Flask" class="text-dark">Powered By Flask</a> /
        <a href="https://getbootstrap.com/" title="Theme By BootStrap" class="text-dark">BootStrap</a> |
        <a href="#" title="A Blog of PhilGao" class="text-dark">CatchPity</a>

    </small>
</footer>
{% endblock footer %}
</body>

</html>

philblog/templates/blog.html
{% extends 'base.html' %}
{% block title %}Phillll{%endblock title%}
{% block content%}
<div class="container justify-content-center text-center py-5">
    <div class="row">
        <div class="col-8 offset-md-2">
            <article class="text-left">
                <h3 class="text-capitalize">{{post.title}}</h3>
                <div class="small pl-1 text-left">
                    <span>Publish on <time datetime="2019-04-15">{{post.createdate}}</time></span>
                </div>
                <p>
                    {%for category in post.categorys%}
                    {%if category and category.id % 8 ==0 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-primary">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 ==1 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-secondary">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 ==2 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-success">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 ==3 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-danger">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 ==4 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-warning">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 ==5 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-info">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 ==6 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-light">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 == 7 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-dark">{{category.category_name}}</a>
                    {%endif%}
                    {%endfor%}
                </p>
                <div>
                    <p>
                    {{post.content|safe}}
                    </p>
                </div>
            </article>
        </div>
    </div>
</div>


{%endblock content%}

philblog/templates/index.html
{% from 'macros.html' import pager %}
{% extends 'base.html' %}
{% block title %}Phillll{%endblock%}
{% block content%}
{% if articles %}
{% for article in articles %}
<div class="container justify-content-center text-center py-5">
    <div class="row">
        <div class="col-8 offset-md-2">
            <section>
                <article class="text-left">
                    <h3><a href="{{url_for('blog.blog',post_id = article.id)}}" class="text-dark text-capitalize">{{article.title}}</a>
                    </h3>
                    <div class="small pl-1">
                        <span>Publish on</span>
                        <time datetime="{{pubdate}}">{{article.createdate}}</time>
                    </div>
                    <div class="pt-2 pr-5">
                        <p>
                            <a href="{{url_for('blog.blog',post_id = article.id)}}">
                                {% if article.showwindow%}
                                    <image class="img-thumbnail" src="{{url_for('static',filename = 'res/image/'+article.showwindow)}}"/>
                                {% else %}
                                    <image class="img-thumbnail" src="{{url_for('static',filename = 'res/image/'+'today.png')}}"/>
                                {% endif %}

                            </a>
                        </p>
                    </div>
                    <div>
                        <a href="{{url_for('blog.blog',post_id = article.id)}}" class="text-dark small">
                            <span>More&gt;&gt;</span>
                        </a>
                    </div>
                </article>
            </section>
        </div>
    </div>

</div>
{% endfor %}
{% else %}
<div>
    <p>There is no posts!</p>
</div>
{% endif %}
{% endblock content%}
{% block pager%}
<div class="container">
    <div class="row">
        <div class="col-8 offset-md-2">
            {{pager(pagination,1)}}
        </div>
    </div>
</div>
{% endblock %}

philblog/templates/macros.html
{% macro static_file(type, filename_or_url,local=True) %}
    {% if local %}
        {% set filename_or_url = url_for('static',filename = filename_or_url )%}
    {% endif %}
    {% if type == 'css'%}
        <link rel="stylesheet" href="{{ filename_or_url }}" type="text/css">
    {% elif type== 'js' %}
        <script type="text/javascript" src="{{ filename_or_url }}"></script>
    {% elif type== 'icon' %}
        <link rel="icon" href="{{ filename_or_url }}">
    {% endif %}
{% endmacro %}

<!--TODO: The first page would show only 2 pages including the first page , this function need rewrite -->
{% macro pager(pagination,fragment)%}
<nav aria-label="Page navigation">
    <ul class="pagination text-dark">
        <li class="page-item text-primary{% if not pagination.has_prev %} disabled {% endif %}">
            <a class="page-link" href="{{url_for(request.endpoint,page = pagination.prev_num)}}">&lt;&lt;</a></li>
        {% for pagenum in pagination.iter_pages(0,fragment,fragment+1,0)%}
        {% if pagenum %}
        <li class="page-item {%if pagenum == pagination.page %} active {% endif %}">
            <a class="page-link" href="{{url_for(request.endpoint,page = pagenum)}}">{{pagenum}}</a></li>
        {% endif %}
        {% endfor %}
        <li class="page-item {% if not pagination.has_next %} disabled {% endif %}">
            <a class="page-link" href="{{url_for(request.endpoint,page = pagination.next_num)}}">&gt;&gt;</a></li>
    </ul>
</nav>
{% endmacro %}

philblog/templates/search.html
<!DOCTYPE html>
<html lang="en">
<header>
    <script type="text/javascript" src="scripts/bootstrap.min.js"></script>
    <script type="text/javascript">
        function search() {
            var content = document.getElementById("searchinput").value
            var request = new XMLHttpRequest();
<!--            request.responseType = "json";-->
            request.onreadystatechange = function () {
                if (request.readyState == 4) {
                    if (request.status == 200) {
                        var jsonObj = JSON.parse(request.responseText);
                        console.log(jsonObj)
                    } else {
                        alert("failed");
                    }
                }
            };
            request.open('GET', "http://127.0.0.1:5000/_search?search="+content,true);
            request.send();
        }

    </script>
</header>
<head>
    <meta charset="UTF-8">
    <title>search</title>
</head>
<body>
    <input type="text" class="form-control" placeholder="Search for..." id='searchinput'>
    <span class="input-group-btn">
        <button class="btn btn-default" type="button"  onclick="search()" id="searchbtn">Go!</button>
    </span>
</body>
</html>

philblog/templates/tag.html
{% extends 'base.html' %}
{% block title %}Phillll{%endblock title%}
{% block content%}

<div class="container justify-content-center text-center py-5">

    <div class="row">
        <div class="col-8 offset-md-2">
            <section>
                <h3>
                    {%for category in categorys%}
                    {%if category and category.id % 8 ==0 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-primary">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 ==1 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-secondary">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 ==2 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-success">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 ==3 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-danger">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 ==4 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-warning">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 ==5 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-info">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 ==6 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-light">{{category.category_name}}</a>
                    {%endif%}
                    {%if category and category.id % 8 == 7 %}
                    <a href="{{url_for('blog.tagged',category_id=category.id)}}" class="badge badge-dark">{{category.category_name}}</a>
                    {%endif%}
                    {%endfor%}
                </h3>
            </section>
        </div>
    </div>
</div>


{%endblock content%}

philblog/templates/tagged.html
{% extends 'base.html' %}
{% block title %}Phillll{%endblock title%}
{% block content%}

<div class="container justify-content-center py-5">

    <div class="row">
        <div class="col-8 offset-md-2">
            <section>
                <h2 class="">{{category.category_name}}</h2>
                {%for article in articles %}
                <a href="{{url_for('blog.blog',post_id = article.id)}}" class="text-left font-italic text-dark">&bull; &nbsp;{{article.title}}</a><br>
                {%endfor%}
            </section>
        </div>
    </div>
</div>
{% endblock%}